### PR TITLE
Fix action repo name

### PR DESCRIPTION
**Pull request by kkaneda**
mathieudutour/github-tag-actions
-> mathieudutour/github-tag-action

### CODE REVIEW

**Comment by kkaneda** [comment]
Let me just merge.

**Comment by kkaneda** [comment]
Hmm, still failing.  :(

```
Run mathieudutour/github-tag-action@v6.2
Previous tag was v0.1.0, previous version was 0.1.0.
Analyzing commit: Define PostProcessor for code refactoring (#49)
The commit should not trigger a release
Analyzing commit: Fix action repo name (#51)

mathieudutour/github-tag-actions
-> mathieudutour/github-tag-action
The commit should not trigger a release
Analysis of 2 commits complete: no release
New version is 0.2.0.
New tag after applying prefix is v0.2.0.
Changelog is ## [0.2.0](https://github.com/llm-operator/job-manager/compare/v0.1.0...v0.2.0) (2024-04-[16](https://github.com/llm-operator/job-manager/actions/runs/8699608001/job/23858499324#step:3:17))

.
Error: Resource not accessible by integration
```

**Comment by Ladicle** [comment]
Maybe because read/write permissions are disabled in `Settings > Actions > General > Workflow permissions`:

image

**Comment by jmuk** [comment]
It is actually configurable on the organization-level settings.  I have enabled it.  Looks like all repositories are changed to read-write now.

Screenshot 2024-04-16 at 11 16 25 AM

**Comment by jmuk** [comment]
New tag is created!  Seemingly the docker build failed but I'll look into that.

**Pull request merged**
