### PR TITLE
Add golangci-lint

### PR DESCRIPTION
**Pull request by kkaneda**

### CODE REVIEW

**Comment by kkaneda** [comment]
@Ladicle , @guangrui-cloudnatix , @jmuk , any feedback appreciated. Might be nice to have, but no strong opinion.

image

**Comment by Ladicle** [comment]
I used this before and found it useful, but I remember turning off some checks in `.golangci.yaml` as it was sometimes a bit annoying.

**Comment by kkaneda** [comment]
I see. Let me make this conservative (`--issues-exit-code=0` and `only-new-issues: true`).

**Review by Ladicle — APPROVED** [review]
golangci-lint contains both golint and errcheck, so we can remove make lint.

**Comment by kkaneda** [comment]
Nice! Let me leave as is but consider it. Currently we run this workflow only at pre-merge, and run `make lint` at both pre-merge and post-merge.

**Pull request merged**
