### PR TITLE
Change helm registry from S3 to ECR

### PR DESCRIPTION
**Pull request by Ladicle**

### CODE REVIEW

**Review by kkaneda — APPROVED** [review]
LG!

Do we need to update ECR?

**Comment by Ladicle** [comment]
I've just created ECR repositories by AWS command. Is there any IaC around public ECR?

BTW, I'm wondering if we can set alias like cloudnatix to 'v8n3t...'.

**Comment by kkaneda** [comment]
Ah, I see. https://github.com/cloudnatix/infra/blob/main/aws/prod/internal/llm/llm.go is the location for ECR public. Let me see if I can import in Pulumi.

> BTW, I'm wondering if we can set alias like cloudnatix to 'v8n3t...'.

True.. I didn't fine the corresponding config in Pulumi. 

https://docs.aws.amazon.com/AmazonECR/latest/public/public-registry-settings.html
https://www.pulumi.com/registry/packages/aws/api-docs/ecrpublic/repository/

Could you try setting the alias from AWS portal?

**Comment by Ladicle** [comment]
done
image

**Comment by Ladicle** [comment]
The custom has yet to be approved, so let me keep the default alias for now.

**Pull request merged**
