### PR TITLE
Use the public ECR for dispatcher.

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Review by kkaneda — APPROVED** [review]

**Comment by kkaneda** [comment]
Btw, any specific reason for using the same image with different tags, instead of having different image names (e.g., `model-manager-server`, model-manager-dispatcher`)?

**Comment by jmuk** [comment]
The image name corresponds with the "repository" of ECR at this time, and so far my implementation was to create an ECR repository for a git repository.  I can change that.

**Comment by kkaneda** [comment]
I see. No strong opinion on either way now. I guess we can change later if we want.

**Comment by jmuk** [comment]
Renamed the URLs accordingly.

**Review by kkaneda — APPROVED** [review]
LG!

**Review by Ladicle — APPROVED** [review]

**Pull request merged**
